language: ruby
rvm:
  - "2.7"
  - "2.6"
  - "2.5"
cache: bundler
before_install:
  - gem update --system
  - nvm install node
env: "EXECJS_RUNTIME=MiniRacer"
matrix:
  include:
    - rvm: "2.7"
      env: "EXECJS_RUNTIME=Node"
