sudo: false
language: ruby
rvm:
  - "2.5"
  - "2.4"
  - "2.3"
git:
  depth: 5
cache: bundler
gemfile:
  - sprockets3.gemfile
  - sprockets4.gemfile
  - mini_racer.gemfile
before_install:
  - nvm install stable
env:
  - EXECJS_RUNTIME=Node
  # mini_racer / rubyracer or rubyrhino depending on platform:
  -
matrix:
  exclude:
    - rvm: "2.3"
      env: "EXECJS_RUNTIME=Node"
    - rvm: "2.3"
      gemfile: mini_racer.gemfile

    - rvm: "2.4"
      gemfile: sprockets3.gemfile

    - rvm: "2.5"
      gemfile: sprockets3.gemfile

    - env: "EXECJS_RUNTIME=Node"
      gemfile: mini_racer.gemfile
